name: Build and deploy ASP.Net Core app to Azure Web App - dekofar-hyperconnect-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_PATH: dekofar-hyperconnect-api/dekofar-hyperconnect-api.csproj
  PUBLISH_DIR: ./publish
  AZURE_WEBAPP_NAME: dekofar-hyperconnect-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: üì• Checkout source code
        uses: actions/checkout@v4

      - name: üõ†Ô∏è Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: üì¶ Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: üèóÔ∏è Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: üöÄ Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --output ${{ env.PUBLISH_DIR }} --no-build

      - name: ‚¨ÜÔ∏è Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: üì• Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-artifact

      - name: üîê Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A551B4260ACB48F183D3F79D46124047 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_36F1DF128C72499E8428BA9650CB35AA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1E6236A3803E492591D3CCAF1A2B122B }}
          auth-type: 'SERVICE_PRINCIPAL'

      - name: üöÄ Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: .
